### PR TITLE
rust: writer automatically breaks chunks at size

### LINKED ISSUE #727: rust: no way to limit chunk size automatically
**Description**

Right now if you write an MCAP with the rust client, you will end up with one large chunk full of all of your messages unless you explicitly call `finish_chunk`. This can result in giant chunks that are larger than `2**31` bytes. This can cause errors in readers which assume that a chunk can be held in memory all at once.

- Version: `releases/rust/v0.5.0`
- Platform: All

**Steps To Reproduce**

**Expected Behavior**

**Actual Behavior**

### PR DESCRIPTION
**Pull request by james-rms**
**Public-Facing Changes**

Adds a new writer option, `chunk_size`, which will automatically break up chunks at a target (uncompressed) size.

**Description**

Fixes #727

### CODE REVIEW

**Comment by james-rms** [comment]
cc. @mrkline

**Review by foxymiles — APPROVED** [review]

File: rust/src/write.rs [hunk 1]
```diff
@@ -765,6 +795,8 @@ impl<W: Write + Seek> ChunkWriter<W> {
                 data: Cow::Borrowed(data),
             },
         )?;
+        // if the chunk is now larger than the chunk size limit, start a new chunk.
```
Comment (james-rms) [inline rust/src/write.rs:798]: remove this

File: rust/src/write.rs [hunk 2]
```diff
@@ -277,6 +293,20 @@ impl<'a, W: Write + Seek> Writer<'a, W> {
...
+        };
+        if let (Some(current_chunk_size), Some(target)) =
+            (current_chunk_size, self.options.chunk_size)
+        {
+            if current_chunk_size > target {
+                self.finish_chunk()?;
+            }
+        }
+
         self.chunkin_time()?.write_message(header, data)?;
```
Comment (jtbandes) [inline rust/src/write.rs:310]: > self.chunkin_time

wut

File: rust/tests/chunks.rs [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+use tempfile::tempfile;
+
+/// Checks that the writer will automatically close chunks when they hit a target size.
+#[test]
+fn auto_cut_chunks() -> Result<()> {
+    let mapped = mcap_test_file()?;
+
+    let messages = mcap::MessageStream::new(&mapped)?;
+
+    let mut tmp = tempfile()?;
```
Comment (jtbandes) [inline rust/tests/chunks.rs:19]: seems like this could be a bit cleaner (and less `unsafe`) if we just write to memory rather than a temp file

**Review by jtbandes — APPROVED** [review]

File: rust/src/write.rs (hunk 2 above)
Comment (mrkline) [reply rust/src/write.rs:310]: It's ~~turtles~~ [memes](https://knowyourmeme.com/memes/its-morbin-time) all the way down.

File: rust/src/write.rs [hunk 4]
```diff
@@ -126,20 +128,34 @@ impl WriteOptions {
...
+    /// specifies the profile that should be written to the MCAP Header record.
     pub fn profile<S: Into<String>>(self, profile: S) -> Self {
         Self {
             profile: profile.into(),
             ..self
         }
     }
 
+    /// specifies the target size of each chunk. Messages will be written to chunks
+    /// until the chunk size is larger than the target chunk size, at which point the
```
Comment (mrkline) [inline rust/src/write.rs:148]: Nit:

```suggestion
    /// specifies the target size of each chunk.
    ///
    /// Messages will be written to chunks until the chunk size
    /// is larger than the target chunk size, at which point the
```

Otherwise rustdoc will put the whole paragraph in the "brief" description.

File: rust/tests/flush.rs [hunk 5]
```diff
@@ -16,7 +16,9 @@ fn flush_and_cut_chunks() -> Result<()> {
     let messages = mcap::MessageStream::new(&mapped)?;
 
     let mut tmp = tempfile()?;
-    let mut writer = mcap::Writer::new(BufWriter::new(&mut tmp))?;
+    let mut writer = mcap::WriteOptions::new()
+        .chunk_size(None)
+        .create(BufWriter::new(&mut tmp))?;
```
Comment (mrkline) [inline rust/tests/flush.rs:21]: Is the goal here just to be explicit? Asking since the default is to not automatically start new chunks.

File: rust/tests/chunks.rs (hunk 3 above)
Comment (mrkline) [reply rust/tests/chunks.rs:19]: Yeah, that's true of all the tests. I think we were originally testing with larger inputs, and I didn't want to assume they could fit in-memory. But now that `mcap_test_file()` is 2 meg, we should just write to a `Vec<u8>`.

I can open a PR to do that unless one of you wants to beat me to it.

File: rust/src/write.rs [hunk 6]
```diff
@@ -277,6 +293,20 @@ impl<'a, W: Write + Seek> Writer<'a, W> {
             .entry(header.channel_id)
             .or_insert(0) += 1;
 
+        // if the current chunk is larger than our target chunk size, finish it
+        // and start a new one.
```
Comment (mrkline) [inline rust/src/write.rs:297]: Should we be explicit (both here and in the docs for the option) that we're talking about a target _uncompressed_ size for the chunk? That seems to be the proximal problem in #727 AIUI - readers might want to make sure an uncompressed chunk will fit in a certain amount of memory.

File: rust/tests/chunks.rs [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+        assert_eq!(ours?, theirs?)
+    }
+
+    // ensure that more than one chunk is present in the new MCAP
+    let num_chunks = mcap::read::LinearReader::new(&mapped)?
+        .filter(|maybe_record| match maybe_record {
+            Ok(mcap::records::Record::Chunk { .. }) => true,
+            _ => false,
+        })
+        .count();
```
Comment (mrkline) [inline rust/tests/chunks.rs:46]:
```suggestion
    let num_chunks = mcap::read::LinearReader::new(&mapped)?
        .filter(|maybe_record| matches!(maybe_record, Ok(mcap::records::Record::Chunk { .. })))
        .count();
```

**Review by mrkline — COMMENTED** [review]
Thanks for making it optional and keeping the existing behavior as the default!

I left it up to users to manually start new chunks with `flush()` because I didn't want to make assumptions about what criteria they want. (Anduril uses several depending on the context - either uncompressed chunk size _and/or_ time since the chunk was started.)

It seems like "max uncompressed size" is a common enough one, and it's built into some of the other writers.

File: rust/tests/chunks.rs (hunk 3 above)
Comment (mrkline) [reply rust/tests/chunks.rs:19]: Yeah, that's true of all the tests. I think we were originally testing with larger inputs, and I didn't want to assume they could fit in-memory. But now that `mcap_test_file()` is 2 meg, we should just write to a `Vec<u8>`.

I can open a PR to do that unless one of you wants to beat me to it.

File: rust/tests/flush.rs (hunk 5 above)
Comment (james-rms) [reply rust/tests/flush.rs:21]: Just being explicit, since we're testing flush here.

File: rust/tests/chunks.rs (hunk 3 above)
Comment (james-rms) [reply rust/tests/chunks.rs:19]: I'll do that here.
