### PR TITLE
fix bad mutation in merge

### LINKED ISSUE #837: `mcap merge` changed channel schema from foxglove.RawImage to foxglove.SceneUpdate
**Description**

- Version: Mcap cli version: `brew info mcap`: `==> mcap: stable 0.0.26 (bottled), HEAD`. The mcap file was recorded with python mcap 1.0.1
- Platform:  mcap cli run on macOS 12.6.1, recording done on Ubuntu 24

`mcap merge` is changing the schema of a particular channel in my mcap files.

**Steps To Reproduce**

I've taken a small mcap recording (attached at the bottom) - just one message long so that the attachment will easily fit in a GitHub issue attachment. Here I use `mcap info` and we see channel `depth_1` has schema `foxglove.RawImage`:

```
❯ mcap info recording000001.mcap
library: python mcap 1.0.1
profile:
messages: 7
duration: 0s
start: 54.911
end: 54.911
compression:
	lz4: [3/3 chunks] [2.12 MiB/519.75 KiB (76.10%)]
channels:
  	(1) bot_entity     1 msgs (+Inf Hz)   : foxglove.SceneUpdate [jsonschema]
  	(2) origin_entity  1 msgs (+Inf Hz)   : foxglove.SceneUpdate [jsonschema]
  	(3) depth_1        1 msgs (+Inf Hz)   : foxglove.RawImage [jsonschema]
  	(4) depth_grid_1   1 msgs (+Inf Hz)   : foxglove.Grid [jsonschema]
  	(5) at_level_og_1  1 msgs (+Inf Hz)   : foxglove.PointCloud [jsonschema]
  	(6) overhead_og_1  1 msgs (+Inf Hz)   : foxglove.PointCloud [jsonschema]
  	(7) frame_debug    1 msgs (+Inf Hz)   : foxglove.SceneUpdate [jsonschema]
attachments: 0
metadata: 0
```

For simplicity in these repro steps, I'm just merging a single file: (The problem occurs too though if I merge two different mcap files though)

```
mcap merge recording000001.mcap -o recording000001_merged.mcap
```

Now inspecting the result, we see the schema on channel `depth_1` has changed:

```
❯ mcap info recording000001_merged.mcap
library: mcap go v1.0.0
profile:
messages: 7
duration: 0s
start: 54.911
end: 54.911
compression:
	zstd: [1/1 chunks] [2.16 MiB/168.80 KiB (92.38%)]
channels:
  	(1) bot_entity     1 msgs (+Inf Hz)   : foxglove.SceneUpdate [jsonschema]
  	(2) origin_entity  1 msgs (+Inf Hz)   : foxglove.SceneUpdate [jsonschema]
  	(3) depth_1        1 msgs (+Inf Hz)   : foxglove.SceneUpdate [jsonschema] # <-- Schema changed from foxglove.RawImage
  	(4) depth_grid_1   1 msgs (+Inf Hz)   : foxglove.Grid [jsonschema]
  	(5) at_level_og_1  1 msgs (+Inf Hz)   : foxglove.PointCloud [jsonschema]
  	(6) overhead_og_1  1 msgs (+Inf Hz)   : foxglove.PointCloud [jsonschema]
  	(7) frame_debug    1 msgs (+Inf Hz)   : foxglove.SceneUpdate [jsonschema]
attachments: 0
metadata: 0
```

**Expected Behavior**

I would expect the schema for the channel `depth_1` would remain `foxglove.RawImage` and not change to `foxglove.SceneUpdate`

Repro data: [repro_data.tar.gz](https://github.com/foxglove/mcap/files/10854152/repro_data.tar.gz)

### PR DESCRIPTION
**Pull request by jtbandes**
**Public-Facing Changes**
Fixed a bug where `mcap merge` would incorrectly change some channels' schemas.
Fixed a bug where `mcap merge` would crash on some input files with schemaless channels (schemaId=0).

**Description**
Fixes #837

### CODE REVIEW

File: go/cli/mcap/cmd/merge.go [hunk 1]
```diff
@@ -226,22 +226,26 @@ func (m *mcapMerger) mergeInputs(w io.Writer, inputs []io.Reader) error {
...
 		if !ok {
-			_, ok := m.outputSchemaID(msg.InputID, newSchema.ID)
-			if !ok {
-				// if the schema is unknown, add it to the output
-				m.addSchema(writer, msg.InputID, newSchema)
+			if schema != nil {
+				_, ok := m.outputSchemaID(msg.InputID, schema.ID)
+				if !ok {
+					// if the schema is unknown, add it to the output
+					m.addSchema(writer, msg.InputID, schema)
```
Comment (wkalt) [inline go/cli/mcap/cmd/merge.go:240]: while we are here, this should get an error check

**Review by james-rms — APPROVED** [review]

**Review by wkalt — APPROVED** [review]
